services:
  db:
    image: mysql:8.0.41
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_docosal
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - docosal-network
  rest-with-spring-boot-docosal:
    image: dougav/rest-with-spring-boot-docosal
    restart: always
    build: ./kotlin-rest-with-spring-boot
    working_dir: /kotlin-rest-with-spring-boot
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring_boot_docosal?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - "80:80"
    expose:
      - 80
    command: sudo mvn spring-boot:run
    depends_on:
      - db
    networks:
      - docosal-network
networks:
  docosal-network:
    driver: bridge